#!/bin/sh
set -eu

image_name="img-tools"
image_tag="latest"

# Build the image if it doesn't exist
if ! docker image inspect "${image_name}:${image_tag}" >/dev/null 2>&1; then
  docker build -t "${image_name}:${image_tag}" "$(dirname "$0")" >/dev/null
fi

docker run --rm -it \
  -v "$(pwd)":/work \
  -w /work \
  "${image_name}:${image_tag}" \
  "$*"
