#!/bin/sh
set -eu

. "$(dirname "$0")/lib/img-docker"

max_px="${1:-1200}"
shift

for f in "$@"; do
  out="${f%.*}-resized.${f##*.}"
  img_run magick "$f" -resize "${max_px}x${max_px}" "$out"
  echo "$f -> $out"
done
